//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Zidrav.rc
//
#define IDS_UPT_READY                   1
#define IDS_UPT_PROCESS                 2
#define IDS_UPT_SCAN                    3
#define IDS_UPT_COMPLETE                4
#define IDS_UPT_CNOCORR                 5
#define IDS_UPT_CCDQGEN                 6
#define IDS_UPT_CCDPGEN                 7
#define IDS_UPT_COMPATCH                8
#define IDS_UPT_ERROCDT                 9
#define IDS_UPT_ERROCDP                 10
#define IDS_UPT_ERROCDQ                 11
#define IDS_UPT_ERROINP                 12
#define IDS_UPT_ERROOUT                 13
#define IDS_UPT_ERROVFILE               14
#define IDS_UPT_ERRODFILE               15
#define IDS_UPT_ERROPFILE               16
#define IDS_UPT_INVCDT                  17
#define IDS_UPT_INVCDP                  18
#define IDS_UPT_INVCDQ                  19
#define IDS_UPT_CVERCHECK               20
#define IDS_UPT_DUPENAMES               21
#define IDS_UPT_CLEAR                   22
#define IDS_UPT_INVMASK                 23
#define IDD_DIALOG1                     101
#define MAIN_DIALOG                     101
#define IDI_ICON1                       103
#define CCHECK_DIALOG                   104
#define MCHECK_DIALOG                   104
#define MPATCH_DIALOG                   105
#define APATCH_DIALOG                   106
#define MREQ_DIALOG                     107
#define FREQ_DIALOG                     108
#define MBCHECK_DIALOG                  109
#define ABOUT_DIALOG                    112
#define IDC_BUTTON2                     1008
#define MAKE_CHECKSUM                   1008
#define CCHECK_INPUT_BUTTON             1008
#define MCHECK_INPUT_BUTTON             1008
#define IDC_BUTTON3                     1009
#define MAKE_PATCH                      1009
#define CCHECK_OUTPUT_BUTTON            1009
#define MCHECK_OUTPUT_BUTTON            1009
#define IDC_BUTTON4                     1010
#define MAKE_REQUEST                    1010
#define MCHECK_GO                       1010
#define IDC_BUTTON5                     1011
#define FILL_REQUEST                    1011
#define MPATCH_OUTPUT_BUTTON            1011
#define IDC_BUTTON6                     1012
#define APPLY_PATCH                     1012
#define ABOUT                           1013
#define ABOUTSTR                        1013
#define MAKE_BATCHCHECKSUM              1014
#define HELP                            1015
#define CCHECK_OUTPUT_FILE              1017
#define MCHECK_OUTPUT_FIELD             1017
#define MPATCH_OUTPUT_FIELD             1018
#define CCHECK_INPUT_FILE               1019
#define MCHECK_INPUT_FIELD              1019
#define CCHECK_BLOCKSIZE_SLIDER         1020
#define MCHECK_BLOCKSIZE_SLIDER         1020
#define CCHECK_BLOCKSIZE_FIELD          1021
#define MCHECK_BLOCKSIZE_FIELD          1021
#define CCHECK_PROGRESS_BAR             1022
#define MCHECK_PROGRESS_BAR             1022
#define MBCHECK_LOWER_PBAR              1024
#define MPATCH_CDT_BUTTON               1028
#define MPATCH_CDT_FIELD                1029
#define MPATCH_VFILE_FIELD              1030
#define MPATCH_VFILE_BUTTON             1031
#define MPATCH_GO                       1032
#define MPATCH_PROGRESS_BAR             1033
#define APATCH_CDP_FIELD                1034
#define APATCH_CDP_BUTTON               1035
#define APATCH_PFILE_FIELD              1036
#define APATCH_PFILE_BUTTON             1037
#define APATCH_STATUS                   1038
#define MREQ_CDT_FIELD                  1039
#define MREQ_CDT_BUTTON                 1040
#define MREQ_DFILE_FIELD                1041
#define MREQ_DFILE_BUTTON               1042
#define MREQ_OUTPUT_FIELD               1043
#define MREQ_OUTPUT_BUTTON              1044
#define FREQ_CDQ_FIELD                  1045
#define FREQ_CDQ_BUTTON                 1046
#define FREQ_VFILE_FIELD                1047
#define FREQ_VFILE_BUTTON               1048
#define FREQ_OUTPUT_FIELD               1049
#define MCHECK_STATUS                   1049
#define FREQ_OUTPUT_BUTTON              1050
#define MPATCH_STATUS                   1050
#define MBCHECK_UPPER_STATUS            1050
#define MREQ_STATUS                     1051
#define MPATCH_MINISTATUS               1051
#define APATCH_GO                       1052
#define MREQ_MINISTATUS                 1052
#define MREQ_PROGRESS_BAR               1053
#define MREQ_GO                         1054
#define FREQ_STATUS                     1055
#define FREQ_GO                         1056
#define MBCHECK_UPPER_PBAR              1057
#define MBCHECK_LOWER_STATUS            1058
#define MBCHECK_PRESERVE                1060
#define MBCHECK_INPUT_FIELD             1061
#define MBCHECK_OUTPUT_FIELD            1062
#define MBCHECK_BLOCKSIZE_SLIDER        1063
#define MBCHECK_INPUT_BUTTON            1064
#define MBCHECK_OUTPUT_BUTTON           1065
#define MBCHECK_BLOCKSIZE_FIELD         1066
#define MBCHECK_GO                      1067
#define MBCHECK_MASK                    1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
